In [62]:
import pandas as pd
import numpy as np

In [2]:
print(pd.__version__)

2.2.2


In [3]:
laptops_df = pd.read_csv('data/laptops.csv')

In [22]:
laptops_df.head(11)

Laptop Status   Brand  \
0   ASUS ExpertBook B1 B1502CBA-EJ0436X Intel Core...    New    Asus   
1   Alurin Go Start Intel Celeron N4020/8GB/256GB ...    New  Alurin   
2   ASUS ExpertBook B1 B1502CBA-EJ0424X Intel Core...    New    Asus   
3   MSI Katana GF66 12UC-082XES Intel Core i7-1270...    New     MSI   
4   HP 15S-FQ5085NS Intel Core i5-1235U/16GB/512GB...    New      HP   
5   MSI Crosshair 17 C12VF-264XES Intel Core i7-12...    New     MSI   
6   Lenovo Thinkpad E14 Gen 4 AMD Ryzen 5 5625U/8G...    New  Lenovo   
7   ASUS VivoBook 15 F515JA-EJ2882W Intel Core i7-...    New    Asus   
8   Medion Akoya E15415 Intel Core i5-10210U/8GB/2...    New  Medion   
9   HP Victus 16-d1038ns Intel Core i7-12700H/16GB...    New      HP   
10  Lenovo V15 IGL Intel Celeron N4020/8GB/256 GB ...    New  Lenovo   

         Model            CPU  RAM  Storage Storage type       GPU  Screen  \
0   ExpertBook  Intel Core i5    8      512          SSD       NaN    15.6   
1           Go  Intel Celeron    8      256          SSD       NaN    15.6   
2   ExpertBook  Intel Core i3    8      256          SSD       NaN    15.6   
3       Katana  Intel Core i7   16     1000          SSD  RTX 3050    15.6   
4          15S  Intel Core i5   16      512          SSD       NaN    15.6   
5    Crosshair  Intel Core i7   32     1000          SSD  RTX 4060    17.3   
6     ThinkPad    AMD Ryzen 5    8      256          SSD       NaN    14.0   
7     VivoBook  Intel Core i7    8      512          SSD       NaN    15.6   
8        Akoya  Intel Core i5    8      256          SSD       NaN    15.6   
9       Victus  Intel Core i7   16      512          SSD  RTX 3050    16.1   
10         V15  Intel Celeron    8      256          SSD       NaN    15.6   

   Touch  Final Price  
0     No      1009.00  
1     No       299.00  
2     No       789.00  
3     No      1199.00  
4     No       669.01  
5     No      1699.00  
6     No       909.00  
7     No       809.01  
8     No       519.00  
9     No      1149.00  
10    No       349.00

In [13]:
print(laptops_df.shape[0])

2160


Laptop          2160
Status          2160
Brand           2160
Model           2160
CPU             2160
RAM             2160
Storage         2160
Storage type    2118
GPU              789
Screen          2156
Touch           2160
Final Price     2160
dtype: int64

In [18]:
print(laptops_df.Brand.value_counts().shape[0])

27


In [28]:
rows = laptops_df.shape[0]
column_count = laptops_df.count()
print(column_count[column_count < rows].shape[0])

3


In [39]:
dell_df = laptops_df[laptops_df.Brand == 'Dell']
dell_df[dell_df['Final Price'] == dell_df['Final Price'].max()]

Laptop Status Brand  \
1335  Dell Precision 5770 Intel Core i7-12700H/16GB/...    New  Dell   

          Model            CPU  RAM  Storage Storage type        GPU  Screen  \
1335  Precision  Intel Core i7   16      512          SSD  RTX A2000    17.0   

     Touch  Final Price  
1335   Yes       3936.0

In [50]:
laptops_df = pd.read_csv('data/laptops.csv')

print('median before: ', laptops_df.Screen.median())

screen_mode = laptops_df.Screen.mode()

laptops_df.Screen = laptops_df.Screen.fillna(value=screen_mode)

print('median after: ', laptops_df.Screen.median())

median before:  15.6
median after:  15.6


In [52]:
innjoo_df = laptops_df[laptops_df.Brand == 'Innjoo']
innjoo_df.head()

Laptop Status   Brand Model  \
1478  InnJoo Voom Excellence Intel Celeron N4020/8GB...    New  Innjoo  Voom   
1479  InnJoo Voom Excellence Pro Intel Celeron N4020...    New  Innjoo  Voom   
1480  Innjoo Voom Intel Celeron N3350/4GB/64GB eMMC/...    New  Innjoo  Voom   
1481  Innjoo Voom Laptop Max Intel Celeron N3350/6GB...    New  Innjoo  Voom   
1482  Innjoo Voom Laptop Pro Intel Celeron N3350/6GB...    New  Innjoo  Voom   

                CPU  RAM  Storage Storage type  GPU  Screen Touch  Final Price  
1478  Intel Celeron    8      256          SSD  NaN    15.6    No       311.37  
1479  Intel Celeron    8      512          SSD  NaN    15.6    No       392.55  
1480  Intel Celeron    4       64         eMMC  NaN    14.1    No       251.40  
1481  Intel Celeron    6       64         eMMC  NaN    14.1    No       383.61  
1482  Intel Celeron    6      128          SSD  NaN    14.1    No       317.02

In [57]:
innjoo_cols_df = innjoo_df[['RAM', 'Storage', 'Screen']]
innjoo_cols_df.head()

RAM  Storage  Screen
1478    8      256    15.6
1479    8      512    15.6
1480    4       64    14.1
1481    6       64    14.1
1482    6      128    14.1

In [60]:
X = innjoo_cols_df.to_numpy()
print(X)

[[  8.  256.   15.6]
 [  8.  512.   15.6]
 [  4.   64.   14.1]
 [  6.   64.   14.1]
 [  6.  128.   14.1]
 [  6.  128.   14.1]]


In [63]:
XT = X.T
print(XT)

[[  8.    8.    4.    6.    6.    6. ]
 [256.  512.   64.   64.  128.  128. ]
 [ 15.6  15.6  14.1  14.1  14.1  14.1]]


In [64]:
XTX = np.matmul(XT, X)
print(XTX)

[[2.52000e+02 8.32000e+03 5.59800e+02]
 [8.32000e+03 3.68640e+05 1.73952e+04]
 [5.59800e+02 1.73952e+04 1.28196e+03]]


In [65]:
y = np.array([1100, 1300, 800, 900, 1000, 1100])
print(y)

[1100 1300  800  900 1000 1100]


In [67]:
w = np.matmul(np.matmul(np.linalg.inv(XTX), XT), y)
print(w)

[45.58076606  0.42783519 45.29127938]


In [68]:
print(np.sum(w))

91.29988062995753
